variables:
  IMAGE_NAME: options-react
  IMAGE_TAG: 1.0

stages:
  - build
  - test

image: $CI_REGISTRY/excelcabinets/options-creator/$IMAGE_NAME:$IMAGE_TAG
deploy_image:
  stage: test
  variables: 
    DOCKER_TLS_CERTDIR: ""
  tags: 
    - prod
  script:
    - echo "works"
    
    
