variables:
  IMAGE_NAME: options-react
  IMAGE_TAG: 1.0

stages:
  - build
  - test

image: docker:20.10.16

services:
    - name: docker:20.10.16-dind
      alias: docker

build_image: 
  stage: build
  before_script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
    - ls
    - cat .env
  script:
    - ls
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/excelcabinets/options-creator/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $CI_REGISTRY/excelcabinets/options-creator/$IMAGE_NAME:$IMAGE_TAG

deploy_image:
  stage: test
  variables: 
    DOCKER_TLS_CERTDIR: ""
  tags: 
    - prod
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $CI_REGISTRY/excelcabinets/options-creator/$IMAGE_NAME:$IMAGE_TAG
    - docker run -d -p 4012:4012 $CI_REGISTRY/excelcabinets/options-creator/$IMAGE_NAME:$IMAGE_TAG
    - docker ps -a


    
    
