variables:
  IMAGE_NAME: options-react
  IMAGE_TAG: 1.0

stages:
  - build

image: docker:20.10.16

services:
    - name: docker:20.10.16-dind
      alias: docker

build_image: 
  stage: build
  before_script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/excelcabinets/options-creator/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $CI_REGISTRY/excelcabinets/options-creator/$IMAGE_NAME:$IMAGE_TAG



    
    
