variables:
  IMAGE_NAME: options-react
  IMAGE_TAG: 1.0

stages:
  - build
  - test

image: docker:20.10.16

deploy_image:
  stage: test
  variables: 
    DOCKER_TLS_CERTDIR: ""
  tags: 
    - prod
  script:
    - docker


    
    
