variables:
  IMAGE_NAME: options-react
  IMAGE_TAG: 1.0

stages:
  - test

show_variables:
  script:
    - echo "CI_REGISTRY:" $CI_REGISTRY
    - echo "CI_REGISTRY_IMAGE:" $CI_REGISTRY_IMAGE
  stage: test