variables:
  IMAGE_NAME: options-react
  IMAGE_TAG: 1.0

stages:
  - build
  - test

image: docker:20.10.16

services:
    - name: docker:20.10.16-dind
      alias: docker

deploy_image:
  stage: test
  variables: 
    DOCKER_TLS_CERTDIR: ""
  tags: 
    - prod
  script:
    - docker build --build-arg API_URL=$API_URL --build-arg DB_USER=$DB_USER -t $IMAGE_NAME:$IMAGE_TAG .
    - docker run -d -p 4012:4012 $IMAGE_NAME:$IMAGE_TAG
    - docker ps -a


    
    
