export interface LotTableInterface {
    builder: string,
    project: string,
    phase: string,
    superintendent?: string,
    phone?: string,
    foreman: string,
    jobID: number,
    boxStyle?: [string, number],
    drawerFronts?: [string, number],
    drawerBoxes?: [string, number],
    drawerGuides?: [string, number],
    doorHinges?: [string, number],
    interiors?: [string, number],
    upperHeight?: string,
    islands?: string,
    crown?: string,
    lightRail?: string,
    baseShoe?: string,
    recyclingBins?: string,
    jobNotes?: string,
    lot?: string,
    plan?: string,
    materialStain?: [string, number],
}

export interface JobInterface {
    builder: string,
    project: string,
    phase: string,
    superintendent?: string,
    phone?: string,
    foreman: string,
    jobID: number,
}