DECLARE @JobIDFK INT = 10171,
		@LotNumber NVARCHAR(50) = '152',
        @RoomID NVARCHAR(50) = 'ades',
        @ConstructionID INT = 1,
        @CabinetCount INT = 1,
        @MaterialID INT = 1,
        @DoorID NVARCHAR(50) = 'ECI-200',
        @FingerpullID NVARCHAR(50) = 'OD-2',
        @DoorQty INT = 1,
        @DoorBuyOutYN INT = 1,
        @GlassDoors NVARCHAR(50) = ' ',
        @GlassShelves NVARCHAR(50) = ' ',
        @ColorID INT = 1,
        @GlazeID INT = 1,
        @InteriorID INT = 1,
        @HingeID INT = 1,
        @HingeQty INT = 1,
        @KnobID NVARCHAR(50) = '113BSN',
        @KnobQty INT = 1,
        @DrawerBoxID INT = 1,
        @DrawerBoxQty INT = 1,
        @DrawerBoxBuyOutYN INT = 1,
        @DrawerGuideID INT = 1,
        @DrawerGuideQty INT = 1,
        @DrawerFrontID INT = 1,
        @PullID NVARCHAR(50) = '102A',
        @PullQty INT = 1,
        @Knob2ID NVARCHAR(50) = ' ',
        @Knob2Qty INT = 1,
        @Pull2ID NVARCHAR(50) = ' ',
        @Pull2Qty INT = 1,
        @HardwareComments NVARCHAR(255) = ' ',
        @AccessoryID INT = 1;

MERGE INTO [EXCELP&D].[dbo].[Lot Order Details] AS target
USING (SELECT [Lot ID] 
       FROM [EXCELP&D].[dbo].[Lots] 
       WHERE [Job IDFK] = @JobIDFK AND [Lot Number] = @LotNumber) AS source ([Lot ID])
ON target.[Lot ID] = source.[Lot ID] AND target.[Room ID] = @RoomID
WHEN MATCHED THEN
    UPDATE SET 
        [Job IDFK] = @JobIDFK,
        [Room ID] = @RoomID,
        [Construction ID] = @ConstructionID,
        [Cabinet Count] = @CabinetCount,
        [Material ID] = @MaterialID,
        [Door ID] = @DoorID,
        [Fingerpull ID] = @FingerpullID,
        [Door Qty] = @DoorQty,
        [DoorBuyOutYN] = @DoorBuyOutYN,
        [Glass Doors] = @GlassDoors,
        [Glass Shelves] = @GlassShelves,
        [Color ID] = @ColorID,
        [Glaze ID] = @GlazeID,
        [Interior ID] = @InteriorID,
        [Hinge ID] = @HingeID,
        [Hinge Qty] = @HingeQty,
        [Knob ID] = @KnobID,
        [Knob Qty] = @KnobQty,
        [Drawer Box ID] = @DrawerBoxID,
        [Drawer Box Qty] = @DrawerBoxQty,
        [DrawerBoxBuyOutYN] = @DrawerBoxBuyOutYN,
        [Drawer Guide ID] = @DrawerGuideID,
        [Drawer Guide Qty] = @DrawerGuideQty,
        [Drawer Front ID] = @DrawerFrontID,
        [Pull ID] = @PullID,
        [Pull Qty] = @PullQty,
        [Knob 2 ID] = @Knob2ID,
        [Knob 2 Qty] = @Knob2Qty,
        [Pull 2 ID] = @Pull2ID,
        [Pull 2 Qty] = @Pull2Qty,
        [Hardware Comments] = @HardwareComments,
        [Accessory ID] = @AccessoryID
WHEN NOT MATCHED THEN
    INSERT ([Lot ID], [Job IDFK], [Room ID], [Construction ID], [Cabinet Count], 
            [Material ID], [Door ID], [Fingerpull ID], [Door Qty], [DoorBuyOutYN], [Glass Doors], [Glass Shelves], [Color ID], 
            [Glaze ID], [Interior ID], [Hinge ID], [Hinge Qty], [Knob ID], [Knob Qty], [Drawer Box ID], [Drawer Box Qty], [DrawerBoxBuyOutYN], 
            [Drawer Guide ID], [Drawer Guide Qty], [Drawer Front ID], [Pull ID], [Pull Qty], [Knob 2 ID], [Knob 2 Qty], [Pull 2 ID], [Pull 2 Qty], [Hardware Comments], [Accessory ID])
    VALUES (source.[Lot ID], 
            @JobIDFK, @RoomID, @ConstructionID, @CabinetCount, 
            @MaterialID, @DoorID, @FingerpullID, @DoorQty, @DoorBuyOutYN, @GlassDoors, @GlassShelves, @ColorID, 
            @GlazeID, @InteriorID, @HingeID, @HingeQty, @KnobID, @KnobQty, @DrawerBoxID, @DrawerBoxQty, @DrawerBoxBuyOutYN, 
            @DrawerGuideID, @DrawerGuideQty, @DrawerFrontID, @PullID, @PullQty, @Knob2ID, @Knob2Qty, @Pull2ID, @Pull2Qty, @HardwareComments, @AccessoryID)
OUTPUT inserted.[Lot ID];